<?php

$ar = json_decode(file_get_contents(__DIR__ . '/../lang/ar.json'), true);

$needed = [
    'Monthly Account Statement',
    'Period',
    'No.',
    'Status',
    'Generated',
    'Financial Overview',
    'Opening Balance',
    'Start of',
    'End of',
    'Credits this period',
    'Debits this period',
    'Closing Balance',
    'Member & Account Details',
    'Full Name',
    'Member No.',
    'Cash Balance',
    'Fund Balance',
    'Monthly Contribution',
    'Cash (Opening)',
    'Fund (Opening)',
    'Period Summary',
    'Opening Balance (brought forward)',
    'Contribution',
    'this period',
    'LATE',
    'Contributions this period',
    'Loan Repayment',
    'due',
    'paid',
    'late fee',
    'Late Fees (period)',
    'Loan Repayments this period',
    'Account Transactions',
    'Date',
    'Description',
    'Account',
    'Type',
    'Amount (SAR)',
    'Cash',
    'Fund',
    'No account transactions recorded for this period.',
    'Loan Standing',
    'Loan ID',
    'Approved Amount',
    'Remaining',
    'Tier',
    'Disbursed',
    'Installments Paid',
    'Next Due',
    'Repayment progress',
    'Overdue Installments',
    'Installment',
    'No active loan at this time.',
    'Compliance Snapshot',
    'Excellent',
    'Fair',
    'Needs Attention',
    'Compliance Score',
    'Based on :count contribution records',
    'Late Contributions',
    'Late Repayments',
    'Current Status',
    'Member Acknowledgment',
    'Statement ID',
    'Certificate of Membership',
    'This is to certify that the following individual is a registered member',
    'Member Fund Management',
    'Total Contributed',
    'Tenure',
    'month',
    'months',
    'Sponsored by',
    'This certificate confirms the membership of the above-named individual in the :brand Fund.',
    'This document is valid as of the date of issue shown below.',
    'Fund Administrator',
    'Member Signature',
    'Issued',
    'This is a computer-generated document.',
    'Loan Repayment Schedule',
    'Loan Details',
    'Loan Amount',
    'Applied',
    'Total Installments',
    'Monthly Installment',
    'Purpose',
    'Repayment Progress',
    'Paid',
    'Amount Remaining',
    'repaid',
    'of',
    'installments',
    'Installment Schedule',
    'Due Date',
    'Paid Date',
    'Late Fee (SAR)',
    'Total',
    'Generated on',
    'Fund Management System',
    'Contribution Receipt',
    'Official receipt for monthly fund contribution',
    'Receipt Details',
    'Receipt Number',
    'Member Number',
    'Contribution Period',
    'Payment Status',
    'ON TIME',
    'Payment Method',
    'Reference Number',
    'Late Fee',
    'Recorded At',
    'Contribution Amount',
    'This receipt confirms that the above contribution has been recorded in the :brand system.',
    'Please retain this document for your records.',
    'This is a computer-generated document. No signature is required.',
];

$missing = [];
foreach ($needed as $key) {
    if (!array_key_exists($key, $ar)) {
        $missing[] = $key;
    }
}

echo 'Missing keys: ' . count($missing) . PHP_EOL;
foreach ($missing as $m) {
    echo $m . PHP_EOL;
}
